#!/bin/bash

if [ "${1}" = "-h" ] || [ "${1}" = "--help" ]; then
  echo -e "Device flash helper scrip:"
  echo -e "$ flashall [options]\n"
  echo -e "Script assumes fastboot being available in the path"
  echo -e "By default only partitions essential to boot are re-flashed"
  echo -e "\t\tboot-ra, ubuntu-seed, snapbootsel(bak), snaprecoverysel(bak)"
  echo -e "\nOptional parameters:"
  echo -e "\t-f | --full: repartition the storage, but do not erase ubuntu-save partition"
  echo -e "\t-H | --hard-reset: same as full + format of ubuntu-save partition"
  echo -e "\t-r | --reboot: reboot device when flashing is completed"
  echo -e "\t-s | --sec <sec.elf file name>: flash passed file to sec partition."
  echo -e "\t\t!!!!Attention: This will likely blow fuses on  your board!!!!!!"
  echo -e "\t-h | --help: this help"
  exit
fi

unset FORMAT REBOOT
while [ "$1" != "" ]; do
    case $1 in
        -f | --repartition)
            REPARTITION="true"
            ;;
        -H | --hard-reset)
            echo "!!!!! Device will be completely erased prior to flashing !!!!!"
            REPARTITION="true"
            FORMAT_HARD="true"
            ;;
        -r | --reboot)
            REBOOT="true"
            ;;
        -s | --sec)
            if [ -e "${2}" ]; then
              SEC_ELF="${2}"
            else
              echo -e "Sec file [${2}] does not exist, pass correct file name!"
              exit
            fi
            shift
            ;;
        --help | -h)
            print_usage
            exit
            ;;
        *)
            # check if this is model assertion
            echo "Unknown parameter '$1'"
            print_usage
            exit
            ;;
    esac
    shift
done

# by default do not flash new partition, only reflash
if [ "${REPARTITION}" = "true" ]; then
  echo "Repartitioning..."
  fastboot flash partition:0 gpt_both0.bin
  fastboot flash partition:1 gpt_both1.bin
  fastboot flash partition:2 gpt_both2.bin
  fastboot flash partition:3 gpt_both3.bin
  fastboot flash partition:4 gpt_both4.bin
  fastboot flash partition:5 gpt_both5.bin

  fastboot erase ddr
  ## lun 1
  fastboot flash xbl_a xbl.elf
  fastboot flash xbl_config_a xbl_config.elf

  ## lun 2
  fastboot flash xbl_b xbl.elf
  fastboot flash xbl_config_b xbl_config.elf

  ## lun 3

  ## lun 4
  # A partitions
  fastboot flash aop_a aop.mbn
  fastboot flash tz_a tz.mbn
  fastboot flash hyp_a hyp.mbn
  [ -e NON-HLOS.bin ] &&  fastboot flash modem_a NON-HLOS.bin
  fastboot flash abl_a abl.elf
  fastboot flash bluetooth_a BTFM.bin
  fastboot flash keymaster_a keymaster64.mbn
  fastboot flash cmnlib_a cmnlib.mbn
  fastboot flash cmnlib64_a cmnlib64.mbn
  fastboot flash ImageFv_a imagefv.elf
  fastboot flash devcfg_a devcfg.mbn
  [ -e dspso.bin ] && fastboot flash dsp_a dspso.bin
  fastboot flash qupfw_a qupv3fw.elf
  fastboot flash storsec_a storsec.mbn
  # b partitions
  # non a/b partitions


  ## lun 5
fi

if [ -n "${SEC_ELF}" ]; then
  echo "!!! Flashing sec partition with ${SEC_ELF} !!!"
  fastboot flash sec ${SEC_ELF}
fi

# Ubuntu partitions
if [ "${FORMAT_HARD}" = "true" ]; then
  echo "Cleaning boot critical partitions"
  fastboot erase ubuntu-save
fi

echo "Flashing Ubuntu images"
fastboot flash boot-ra boot.img
fastboot flash snaprecoverysel snaprecoverysel.bin
fastboot flash snaprecoveryselbak snaprecoverysel.bin
fastboot flash snapbootsel snapbootsel.bin
fastboot flash snapbootselbak snapbootsel.bin
fastboot flash ubuntu-seed ubuntu-seed.img

if [ "${REBOOT}" = "true" ]; then
  fastboot reboot
fi
