#!/bin/sh

if [ "${1}" = "-h" ] || [ "${1}" = "--help" ]; then
  echo -e "Device flash helper scrip:"
  echo -e "$ flashall [options]\n"
  echo -e "Script assumes fastboot being available in the path"
  echo -e "By default only partitions essential to boot are re-flashed"
  echo -e "\t\tboot_ra, ubuntu-seed, snapbootsel(bak), snaprecoverysel(bak)"
  echo -e "\nOptional parameters:"
  echo -e "\t-f | --full: repartition emmc, but do not erase ubuntu-save partition"
  echo -e "\t-H | --hard-reset: same as full + format of ubuntu-save partition"
  echo -e "\t-r | --reboot: reboot device when flashing is completed"
  echo -e "\t-h | --help: this help"
  exit
fi
unset FORMAT REBOOT
while [ "$1" != "" ]; do
    case $1 in
        -f | --repartition)
            REPARTITION="true"
            ;;
        -H | --hard-reset)
            echo "!!!!! Device will be completely erased prior to flashing !!!!!"
            REPARTITION="true"
            FORMAT_HARD="true"
            ;;
        -r | --reboot)
            REBOOT="true"
            ;;
        --help | -h)
            print_usage
            exit
            ;;
        *)
            # check if this is model assertion
            echo "Unknown parameter '$1'"
            print_usage
            exit
            ;;
    esac
    shift
done

# by default do not flash new partition, only reflash
if [ "${REPARTITION}" = "true" ]; then
  echo "Repartitioning..."
  fastboot flash partition:0 gpt_both0.bin
  fastboot flash partition:1 gpt_both1.bin
  fastboot flash partition:2 gpt_both2.bin
  fastboot flash partition:3 gpt_both3.bin
  fastboot flash partition:4 gpt_both4.bin
  fastboot flash partition:5 gpt_both5.bin

  fastboot flash ImageFv_a imagefv.elf
  fastboot flash aop_a aop.mbn
  fastboot flash bluetooth_a BTFM.bin
  fastboot flash cmnlib64_a cmnlib64.mbn
  fastboot flash cmnlib_a cmnlib.mbn
  fastboot erase ddr
  fastboot flash devcfg_a devcfg.mbn
  fastboot flash dsp_a dspso.bin
  fastboot flash hyp_a hyp.mbn
  fastboot flash keymaster_a keymaster64.mbn
  fastboot flash qupfw_a qupv3fw.elf
  fastboot flash storsec_a storsec.mbn
  fastboot flash tz_a tz.mbn
  fastboot flash xbl_a xbl.elf
  fastboot flash xbl_config_a xbl_config.elf
  fastboot flash abl_a abl.elf
fi

if [ "${FORMAT_HARD}" = "true" ]; then
  echo "Erasing save partition!!!"
  fastboot erase save
fi

fastboot flash boot_a boot.img
fastboot flash boot_r boot.img
fastboot flash snapbootsel snapbootsel.bin
fastboot flash snapbootselbak snapbootsel.bin

fastboot flash seed seed.img

if [ "${REBOOT}" = "true" ]; then
  fastboot reboot
fi
