name: rb3
version: 18-1
summary: RB3 (Dragonboard 845) support package
description: |
 Support files for booting RB3 (Dragonboard 845) board
type: gadget

base: core18

architectures:
  - build-on: [amd64, arm64]
    run-on: arm64

confinement: strict
grade: stable

parts:
    prebuilt:
        plugin: dump
        source: prebuilt
        organize:
            '*': blobs/



